# Generated by Django 5.0 on 2024-04-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='message',
        ),
    ]
