# Generated by Django 5.0 on 2024-04-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_employee_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='details',
        ),
    ]
